name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Set Github Token environment variable
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: echo "export TF_VAR_github_token=${TOKEN_GITHUB}" >> $GITHUB_ENV

      - name: Terraform Apply
        env:
          TF_LOG: DEBUG
        run: |
          terraform init
          terraform plan -var "token=${TF_VAR_github_token}"
          terraform apply -auto-approve -var "token=${TF_VAR_github_token}"
